# Generated by Django 4.1 on 2023-02-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_otp_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
