# Generated by Django 4.1 on 2023-02-15 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_information_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information', to='Shop.product'),
        ),
    ]
